---
title: "gayrights-lit"
output: html_document
date: "2023-05-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#On Examining Attitudes toward Homosexuality 

Both rights and attitudes toward homosexuality has increased overtime, and this trend has been noticed by many polls and researchers. As such, studies in this field have examined what are the determinants that shape the opinion toward homosexuality. Many of previous studies, however, have focused on a single country due to the sparsity and incomparability of survey data with relevant questions. While a few cross-national studies help bring comparative perspective as well as identify important factors at the country-level, a scarcity of cross-national studies leave a room for necessity of confirmation of these findings [@Adamczyk2019]. In an ideal world, we would like to have the full time series of every country and every year with different dimensions of homosexuality rights. We are, unfortunately, not living in that universe. As a possible next best option, we propose TOL-H data which is a comprehensive dataset on the attitudes toward homosexuality based on available survey data across the world. Before introducing TOL-H, this section will provide a brief overview of studies of attitudes toward homosexuality.

Changes in attitudes overtime and determinants of opinion shifts are key questions in public opinion studies. To assess these questions, it is important to have longitudinal survey data. United States is one of a few data rich countries in this regard, having been asked LGBTQ-related issue questions dated back more than 50 years (e.g., General Social Survey (GSS) in 1973). Based upon data availability, many initial studies have examined United States to understand what shapes the attitudes toward homosexuality. 

For example, @lee2019changing evaluated changes of attitudes toward same-sex marriage between 2008 and 2016 by using three waves of national online panel survey. Thy found that increase in level of education and interpersonal contact with LGBTQ+ community as well as decrease in religiosity increase the support for same-sex marriage. Daniels [-@daniels2019evolution] also examined the same rights but using data from the Pew Research Center and the National Opinion Research Center with temporal range between 1998 and 2014. This study found that ideology, partisanship, personnel connection, religion, and generation have impacts on forming attitudes toward homosexuality. Looking at different LGBTQ+ rights (namely, conversion therapy and denials of service based on religious beliefs), Flores, Mallory, and Conron [-@flores2020public] illustrated that some of individual features – such as age, race, party affiliation, education level, and interpersonal contact – could be occasionally inconsistent with previous findings. 

More recent studies opinion towards homosexuality in different countries such as Chile [@paradela2023much], Japan [@naka2022gendered], South Korea [@rich2020proximity], and Taiwan [@cheng2016changing]. Overall, these studies echo with the previous studies especially from US, which emphasizes the importance of socioeconomic feature in forming tolerance toward homosexuality; these studies, however, also presented contextual differences between Western and non-Western countries in terms of opinion toward homosexuality. 

Collectively, studies focused on single country over time contribute our understanding in attitudes toward homosexuality in two folds. First, they enable us to understand the overtime changes in attitudes. Second, studies illustrate individual level features that form the opinion toward homosexuality. That said, single country focused studies are less interested in country-level factors.

In comparison to single-country studies, relatively small portion of cross-national over time studies have conducted. These studies have used regional (e.g., Eurobarometer, European Values Study, Latinobarometer) or global surveys (e.g., International Social Survey Programme, Pew Global Attitudes Project, or World Values Survey) as primary data sources and are more engaged with finding country-level characteristics that shape opinions toward homosexuality. Both poll data and studies have found that public opinion have been changed toward more liberal direction across the world [@corrales2017understanding; @hadler2012influence], although some conservative shifts have been found [@strand2011kill]. In addition, previous studies have illustrated that features such as economic development [@hooghe2013same], historical legacy [@asal2013original], political context [@zhang2019tolerance], and religious context [@van2013disapproval] have an impact on shaping the opinion toward homosexuality.^[We would like to note that studies on attitudes toward homosexuality also have examined individual level features. Previous studies have found that individual contexts – such as age [@finke2008cross], education [@kozloski2010homosexual; @lambert2006college], gender [@dodge2016attitudes; @rye2010self], direct or indirect linkage [@becker2012determinants; @brewer2007value; @lee2019changing], and religion [@hooghe2013same; @sherkat2010race] – have an impact on shaping attitudes. However, these are not actively discussed in the main text because the current study’s focus is at the country-level with comparative perspectives.] 

The issue, however, is that some of previous findings conflict with each other.^[Conflicting conclusions are also found from the studies that focused on individual-level factors.]  For example, many cross-national studies as well as a few single-country studies have examined postmaterialist idea [@inglehart1990culture; @inglehart2000modernization], which indicates modernized societies will have greater level of social tolerance. Using the same data source (WVS) with different in spatial and temporal coverage, Andersen and Fetner [-@andersen2008economic] and Zhang and Brym [-@zhang2019tolerance] reached out to the different conclusions. Focusing on 35 democracies between 1990 and 2002, Andersen and Fetner [-@andersen2008economic] found that national economic context is important factor of shaping public opinion toward homosexuality. Increasing both geographical and temporal coverage (88 countries between 1981 and 2014), however, Zhang and Brym [-@zhang2019tolerance] showed that economic development is not as substantial as previous studies found. Moreover, they found that economic inequality does not affect attitudes on homosexuality.

Less intense but still important discrepancies are found with different country-level factors. For instance, many of previous studies have highlighted the importance of religion as an important feature that shapes the attitudes toward homosexuality both at the individual level [@adamczyk2017cross; @adamczyk2016place; @finke2008cross; @sherkat2010race; @van2013disapproval] and country level [@adamczyk2017cross; @asal2013original; @finke2008cross]. Specifically, studies have shown that a country’s dominant religion or overall level of religiosity can shape [@adamczyk2009shaping; @finke2008cross; @van2013disapproval]. Some studies, however, have noticed the decline role of the religion [see @lee2019changing] and the importance of considering cultural differences (e.g., impact of cultural taboos or cultural orientation) with religious impact [@adamczyk2009shaping].

On top of conflicting findings, two limitations further stand out from previous studies. First, from our knowledge, there is no comprehensive cross-national longitudinal data available to researchers. As discussed earlier, a few countries are rich on single country over time data, but most countries do not have that benefits. Obtaining cross-country over time data is much harder, and therefore, many cross-country studies have examined a handful countries with a small-time span. More recent studies take the advantage of survey data across the world [e.g., @zhang2019tolerance], although these are only a few exceptional cases. 

In addition, most of available cross-national survey data have regional focus. This leads to researchers focus more on data rich regions such as North America and Europe. This is concerning because it will only allow to have a partial picture of attitudes toward homosexuality. For example, the phases of tolerance toward homosexuality and developing legal rights of same sex couples vary across countries as well as regions such as Asian vs. Western European countries or even Eastern and Central European countries vs. Western European countries [@vstulhofer2009determinants]. With regionally focused data, it is difficult to see broader change in attitudes cross-nationally. In other words, limitations in data, in terms of both temporal and spatial scope, hampers comprehensive understanding of attitudes toward homosexuality. 

Second, it is difficult to properly address the impact of phrases used in the survey. Even when researchers acknowledge the limitations of relying on one data source (e.g, WVS) for cross-national studies, it is difficult or even potentially erroneous to simply utilize different survey data in one study. Studies and polls have used different terms –such as gay, lesbian, same-sex, or homosexuality – to indicate LGBTQ-related issues [@Adamczyk2019]. Putting aside whether the public can distinguish the terms, certain phrases – namely gay and homosexuality – are more exposed to and used by the public than the others. Given that question wording can have an impact on the responses [@clifford2021increasing; @zaller1992nature], not dealing with question difficulty that stems from wordings is concerning. Smith et al. [-@smith2018gay], for instance, examined the wording impact between “homosexual” and “gay and lesbian”. The study found that the survey participants respond differently about their attitudes toward “homosexual rights” and “gay and lesbian rights” based on the group identity and social attitude. Other studies also echo the impacts of phrasing on public support [@hill2005development; @husser2016gay; @lewis2017degrees]. Therefore, dealing with question wordings is another hurdle that needs to be properly addressed.

Acknowledging disagreements of previous studies’ findings and limitations in terms of data, this paper aims to introduce TOL-H data for those who are interested in attitudes toward homosexuality. We expect to achieve two goals. First, TOL-H data will facilitate more cross-national studies in this field. TOL-H is a cross-national overtime data from available public opinion survey data from various countries across the world; therefore, it opens more opportunity to explore questions that couldn’t be answered with a single country data or a longitudinal data with a few countries. Using the IRT adds additional merits because it helps deal with the usage of different terms across surveys. Second, attitudes toward homosexuality are multifaceted. Like other issue areas, LGBTQ-related issues are composed of different topics such as individual comfortability/tolerance [@monto2014discomfort], employment [@becker2014employment], marriage [@baunach2012changing], and parenting [@webb2014heterosexual]; these are primary issues that have been asked by pollsters. Previous studies, however, mostly examined only one dimension. Using our TOL-H data, researchers can easily access to different LGBTQ-related issues at one venue that covers a wide range of temporal and geographical scopes.

