---
format:
  pdf:
    number-sections: false

bibliography: 
tables: true # enable longtable and booktabs
fontsize: 12pt
indent: true
geometry: margin=1in
linestretch: 1.5 # double spacing using linestretch 1.5
colorlinks: true

execute:
  echo: false
  message: false
  warning: false
  dpi: 300
    
title: |
  | Public Support for Gay Rights
  | Across Countries and Over Time
subtitle: |
  Memo to Editor and Reviewers
---

We first want to thank the Editor and the reviewers for their helpful comments and suggestions. We revised our original manuscript according to comments from both Reviewer 1 and Reviewer 2. Below we summarize our revisions and explanations on how we reflect the valuable comments in our revised manuscript:

-   **Further Explanations on Figure 4.** Reviewer 1 recommends us to provide more meaningful explanations rather than just the statistical formula. We fully agree with the importance of the explanations.

    In the current version of our manuscript, we include further explanation about the reasons why some countries which do not recognize same-sex marriage such as Japan and India rank higher than other countries including Taiwan legalizing same-sex marriage. It is because the SGR index is to measure public opinion toward gay rights rather than the existence of laws for same-sex marriage. In other words, the aggregated public opinion index toward gay rights might differ from the law itself.

-   **Defining the purpose of the manuscript.** Reviewer 2 points that our manuscript should define the purpose of paper. Given that clarifying the main purpose is a crucial part of a manuscript, we revise our manuscript in order to emphasize the purpose of this paper.

    In the revised manuscript, we clarify that our article aims to overcome limitations of previous studies on public opinion for gay rights by introducing the SGR dataset and to facilitate studies on public opinion about gay rights. The explanation is made in the very first paragraph. Moreover, we modify some sentences throughout the manuscript in order to re-emphasize the purpose of our paper. For instance, we reiterate this article tries to overcome previous limitations concerning data about public opinion in the concluding section.

-   **Clarifying our focus on "support for gay rights" rather than others.** Reviewer 2 mentioned that, "Why are gays rights used and not another concept?". We again fully agree with the importance of providing explanations on the reasons why we focus on gay's rights rather than other concepts.

    In this study, we chose to use the concept and term gay rights primarily to align with the language used in the survey questions, which mostly refer to gay, lesbian, and same-sex couples (see Appendix Table A2 for more information). Since our public opinion data (and thus the SGR dataset) spans multiple decades, dating back as early as the 1970s, we aimed to remain consistent with the original wording and concepts of these surveys. We recognize that LGBTQ+ is more inclusive of sexual orientations and gender identities and reflects current discourse. However, for the purposes of this paper, focusing on gay rights allows us to maintain alignment with the original context of the survey questionnaires.

-   **Detailed explanation on how we select indicators used in the Support for Gay Rights Latent Variable Model.** Reviewer 2 also gives us advice that it might be better for us to provide detailed explanations on the selection of indicators used in our Latent Variable Model. We cannot agree more given that the indicators are the core part of constructing our model and index. Thus, we revised our manuscript to clearly deliver the information on the indicators.

    In the revised manuscript, we carefully explain our process of the selection of indicators. To build the SGR dataset, we collected a comprehensive collection of survey questionnaires according to the topic. As mentioned in the revised manuscript, we collected four groups of questions capturing the public latent attitude toward gay rights. First, we collect questions about public approval and acceptance of homosexuals and homosexuality. Second, questions exploring public support for the legalization of same-sex marriage are also considered. Third, we take into account of questions regarding public opinion on the rights of gay, lesbian, and bisexual individuals, including equal rights to heterosexual individuals. Fourth, we also consider questions about attitudes for homosexual individuals’ social and political roles, for instance, running for public office. 

  	Further details about survey items used to estimate support for gay rights are presented in the Appendix B. Moreover, the explanations about how to construct the SGR data based on the survey questions are detailly described in the Appendix C along with the explanations on the DCPO model. We are definitely sure that our revisions based on the comment make our manuscript much more readable.

-   **Differences of our dataset compared to GAI and Limitations of our dataset.** Reviewer 2 also recommends that we should differentiate our dataset from already existing dataset such as GAI. Moreover, the reviewer suggests that explanations on potential limitations of our dataset should be provided. We are definitely on the line with the comments.

    First, we moved explanation concerning GAI and its limitations to the main text. As explained in the revised manuscript, the GAI estimates are only available for a single cross-section, making analysis of change over time impossible. Thus, even though the GAI is also based on the latent-variable estimation, it does not provide opportunities for scholars to examine the changes in the public attitude toward gay rights. The SGR dataset overcomes this limitation by providing estimates of support for gay rights both cross-nationally and longitudinally.

    We also revised our manuscript by mentioning the potential limitations of our dataset. We note that the coverage of our SGR dataset depends on the availability of the source of survey data. Furthermore, we point out that researchers should pay attention to the uncertainty in the SGR dataset and should take it into account.

We appreciate for all comments and advice from both reviewers. We believe that our revised manuscript is now much more nuanced compared to the previous version. Again, we thank the reviewers for the valuable and warmful comments and the opportunity to revise our manuscript.

# Reference {.unnumbered}
